AWH_staging/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('search/', include('search.urls')),

    path('warehouse/', include('warehouse.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path

from . import views

app_name= 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    ]

search/urls.py
from django.urls import path

from . import views

app_name= 'search'

urlpatterns = [
    path('results/', views.SearchView, name='searchresults'),


]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


from . import views

app_name= 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('profile_edit/', user_views.profile_edit, name='profile_edit'),
    path('profile/', user_views.profile, name='profile'),
    path('register/', user_views.register, name='register'),

]

warehouse/urls.py
from django.urls import path
from . import views
from .views import SongDeleteView
# SongUpdateView

app_name= 'warehouse'

urlpatterns = [
    path('', views.index, name='index'),
    path('song/new/', views.AddSong, name='addSong'),
    # path('song/<int:pk>/update/', SongUpdateView.as_view(), name='song-update'),
    path('song/<int:pk>/delete/', SongDeleteView.as_view(), name='song-delete'),
    path('success/', views.success, name='success'),
    path('album/<int:album_id>/', views.ListSongByAlbum, name='listsongbyalbum'),
    path('artist/<int:artist_id>/', views.ListSongByArtist, name='listsongbyartist'),
    path('detail/<int:song_id>', views.SongDetailView, name='SongDetail'),

]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from warehouse.models import Artist, Album, Song, Rating



def index(request):
    all_artist_list = Artist.objects.order_by('followers')[:10]
    context = {'all_artist_list': all_artist_list}
    return render(request, 'homepage/home.html', context)
# Create your views here.

homepage/templates/homepage/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'homepage/main.css' %}">



    {% if title %}
        <title>Album WareHouse - {{ title }}</title>
    {% else %}
        <title>Album WareHouse</title>
    {% endif %}
  </head>
  <body>
    <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Album WareHouse</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{% url 'homepage:index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'warehouse:index' %}">Artists</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            <form class='d-flex' method=POST action="{% url 'search:searchresults' %}">
              {% csrf_token %}
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searched" >
              <span> &nbsp; </span>
              <button class="btn btn-outline-su=secondary" type="submit" style="background: #FFFFFF;">Search </button>
            </form>
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
              {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <!-- <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div> -->
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/homepage/home.html
{% extends 'homepage/base.html' %}
{% block content %}


<h1>Top 10 Artists</h1>
<p>{{ signin_msg}} </p>


{% if all_artist_list %}
    <ul>
    {% for artist in all_artist_list %}
        <li><a href="{% url 'warehouse:listsongbyartist' artist.id %}">{{ artist.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No artists are available.</p>
{% endif %}
{% endblock content%}