AWH_staging/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('search/', include('search.urls')),

    path('warehouse/', include('warehouse.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


from . import views

app_name= 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('profile_edit/', user_views.profile_edit, name='profile_edit'),
    path('profile/', user_views.profile, name='profile'),
    path('register/', user_views.register, name='register'),

]

warehouse/urls.py
from django.urls import path
from . import views
from .views import SongDeleteView
# SongUpdateView

app_name= 'warehouse'

urlpatterns = [
    path('', views.index, name='index'),
    path('song/new/', views.AddSong, name='addSong'),
    # path('song/<int:pk>/update/', SongUpdateView.as_view(), name='song-update'),
    path('song/<int:pk>/delete/', SongDeleteView.as_view(), name='song-delete'),
    path('success/', views.success, name='success'),
    path('album/<int:album_id>/', views.ListSongByAlbum, name='listsongbyalbum'),
    path('artist/<int:artist_id>/', views.ListSongByArtist, name='listsongbyartist'),
    path('detail/<int:song_id>', views.SongDetailView, name='SongDetail'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from warehouse.models import Artist

class Profile(models.Model):
    user= models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    followed_artists = models.ManyToManyField(Artist, blank='No followed artists yet')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args,**kwargs):
        super().save(*args,**kwargs)

        img = Image.open(self.image.path)

        if img.height>300 or img.width >300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)
# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2',]

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email',]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from .models import Profile, Artist

def register(request):
    if request.method== 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            messages.success(request, f'Your account has been created! You are now logged in')
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],
                                    )
            login(request, new_user)
            return redirect('/')
    else:
        form = UserRegisterForm()

    return render(request, 'users/register.html', {'form': form})


@login_required
def profile_edit(request):
    template_name = 'profile_edit'

    if request.method== 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid:
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'users/profile_edit.html', context)

@login_required
def profile(request):
    template_name = 'profile'
    # followed_artists_list = request.user.followers_set.all()
    followed_artists_list = Artist.objects.filter(followers=request.user)
    # profile_obj = Profile.objects.get(user=request.user)
    # followed_artists_list = profile_obj.followed_artists
    context = {
        'followed_artists_list': followed_artists_list,
    }
    return render(request, 'users/profile.html', context)

# Create your views here.


# Create your views here.

users/templates/users/login.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-info" type="submit" name="login"> Log In</button>
          <small class="text-muted ml-2">
              <a href="{% url 'users:password_reset' %}">Forgot Password?</a>
          </small>
        </div>
    </form>
    <div class="border-top pt-3">
      <small class="text-muted">
        Need an account? <a class='ml-2' href="{% url 'users:register' %}">Sign Up</a>
      </small>
    </div>
  </div>
{% endblock content%}

users/templates/users/logout.html
{% extends 'homepage/base.html' %}

{% block content %}
  <h2>You have been logged out</h2>
    <div class="border-top pt-3">
      <a href="{% url 'users:login' %}">Log In Again</a>
    </div>
  </div>
{% endblock content%}

users/templates/users/password_reset.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-info" type="submit"> Request Password Reset</button>
        </div>
    </form>
  </div>
{% endblock content%}

users/templates/users/password_reset_complete.html
{% extends 'homepage/base.html' %}
{% block content %}
    <div class="alert alert-info">
            Your password has been set
    </div>
    <a href="{% url 'users:login' %}">Sign In Here</a>
{% endblock content%}

users/templates/users/password_reset_confirm.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-info" type="submit"> Reset Password </button>
        </div>
    </form>
  </div>
{% endblock content%}

users/templates/users/password_reset_done.html
{% extends 'homepage/base.html' %}

{% block content %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password

    </div>
{% endblock content%}

users/templates/users/profile.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
      <div class="media-body">
        <h2 class="account-heading">{{user.username}}</h2>
        <span style="float:right;">
         <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'users:profile_edit' %}">Edit Info</a>
        </span>
        <p class="text-secondary">{{user.email}}</p>

      </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Profile Info</legend>
          Followed artists:
          {% for artist in followed_artists_list %}
            <a href="{% url 'warehouse:listsongbyartist' artist.id %}">{{artist}}</a>
          {% endfor %}
        </fieldset>
    </form>
  </div>
{% endblock content%}

users/templates/users/profile_edit.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
      <div class="media-body">
        <h2 class="account-heading">{{user.username}}</h2>
        <p class="text-secondary">{{user.email}}</p>
      </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Profile Info</legend>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    </form>
  </div>
{% endblock content%}

users/templates/users/register.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Join Today</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-info" type="submit" name="Sign Up">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-3">
      <small class="text-muted">
        Already have an account? <a class='ml-2' href="{% url 'users:login' %}">Sign In</a>
      </small>
    </div>
  </div>
{% endblock content%}