AWH_staging/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('search/', include('search.urls')),

    path('warehouse/', include('warehouse.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


from . import views

app_name= 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('profile_edit/', user_views.profile_edit, name='profile_edit'),
    path('profile/', user_views.profile, name='profile'),
    path('register/', user_views.register, name='register'),

]

warehouse/urls.py
from django.urls import path
from . import views
from .views import SongDeleteView
# SongUpdateView

app_name= 'warehouse'

urlpatterns = [
    path('', views.index, name='index'),
    path('song/new/', views.AddSong, name='addSong'),
    # path('song/<int:pk>/update/', SongUpdateView.as_view(), name='song-update'),
    path('song/<int:pk>/delete/', SongDeleteView.as_view(), name='song-delete'),
    path('success/', views.success, name='success'),
    path('album/<int:album_id>/', views.ListSongByAlbum, name='listsongbyalbum'),
    path('artist/<int:artist_id>/', views.ListSongByArtist, name='listsongbyartist'),
    path('detail/<int:song_id>', views.SongDetailView, name='SongDetail'),

]

warehouse/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.db.models import Avg

# Create your models here.
class Artist(models.Model):
    name= models.CharField(max_length=200)
    followers= models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='following', null=True)

    @property
    def average_rating(self):
        songs_by_artist= Song.objects.filter(artist=self)
        rating_list = [song.average_rating for song in songs_by_artist]
        if len(rating_list)>0:
            return round(sum(rating_list)/len(rating_list),2)
        else:
            return 0
    @property
    def rating_count(self):
        songs_by_artist= Song.objects.filter(artist=self)
        rating_list_count = len(Rating.objects.filter(song__in= songs_by_artist).exclude(rate__exact=0))
        return round(rating_list_count,2)

    def __str__(self):
        return self.name

class Album(models.Model):
    name= models.CharField(max_length=200)

    @property
    def average_rating(self):
        songs_in_album= Song.objects.filter(album_id=self.id)
        rating_list = [song.average_rating for song in songs_in_album]
        return round(sum(rating_list)/len(rating_list),2)

    @property
    def rating_count(self):
        songs_in_album= Song.objects.filter(album_id=self.id)
        rating_list_count = len(Rating.objects.filter(song__in= songs_in_album).exclude(rate__exact=0))
        return round(rating_list_count,2)


    def __str__(self):
        return self.name

class Song(models.Model):
    name = models.CharField(max_length=200)
    artist = models.ManyToManyField(Artist)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name='songs')

    @property
    def average_rating(self):
        try:
            return round(self.rating_set.exclude(rate__exact=0).aggregate(Avg('rate'))['rate__avg'],2)
        except:
            return 0
    @property
    def user_ratings(self):
        if self.rating_set.all().exists():
            return self.rating_set.filter(song=self, user=request.user)
        else:
            return 0

    def __str__(self):
        return self.name


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    rate = models.PositiveSmallIntegerField(blank=True, null=True, validators=[MinValueValidator(1), MaxValueValidator(10)])

    created = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

warehouse/forms.py
from django import forms
from warehouse.models import Rating, Artist, Album, Song

class RateForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['rate',]

class ArtistForm(forms.ModelForm):
    class Meta:
        model= Artist
        fields = ['name',]
        labels = {'name': 'Artist Name(s)',}


class AlbumForm(forms.ModelForm):
    class Meta:
        model= Album
        fields = ['name',]
        labels = {'name': 'Album Name',}


class SongForm(forms.Form):
    # class Meta:
    #     model = Song
    name = forms.CharField(label= "Song Name", max_length=32, required=True)
    artist = forms.CharField(label= "Artist Name(s)",max_length=32, required=True)
    album = forms.CharField(label= "Album Name",max_length=32, required=True)

warehouse/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponse
from .models import Artist, Album, Song, Rating
from django.urls import reverse
from django.views import generic
from warehouse.forms import RateForm, SongForm, ArtistForm, AlbumForm
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

def success(request):
    return render(request, 'warehouse/success.html')

def index(request):
    all_artist_list = Artist.objects.order_by('name')
    context = {'all_artist_list': all_artist_list}
    return render(request, 'warehouse/index.html', context)

def ListSongByAlbum(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    all_song_list = Song.objects.filter(album__id=album_id)
    rating_dict = {}
    signin_msg = ''

    if request.user.is_anonymous == False:
        for song in all_song_list:
            if Rating.objects.filter(song=song, user=request.user).values('rate').first() is not None:
                rating_dict[song] = Rating.objects.filter(song=song, user=request.user).values('rate').first()['rate']

    else:
        for song in all_song_list:
            rating_dict[song] = '-'
        signin_msg = 'Please create an account or log in to rate songs and follow artists'

    context = {'album': album,
    'all_song_list': all_song_list,
    'rating_dict': rating_dict,
    'signin_msg': signin_msg}
    #'songs_without_rating': songs_without_rating,}
    return render(request, 'warehouse/listsongbyalbum.html', context)

def ListSongByArtist(request, artist_id):
    artist = get_object_or_404(Artist, pk=artist_id)
    all_song_list = Song.objects.filter(artist__id=artist_id)
    rating_dict = {}
    signin_msg = ''

    if request.user.is_anonymous == False:
        for song in all_song_list:
            if Rating.objects.filter(song=song, user=request.user).values('rate').first() is not None:
                rating_dict[song] = Rating.objects.filter(song=song, user=request.user).values('rate').first()['rate']

        #Follow/Unfollow Artist
        if request.method == "POST":
            current_user = request.user
            action = request.POST['follow']
            if action == 'unfollow':
                current_user.following.remove(artist)
            elif action == 'follow':
                current_user.following.add(artist)
            current_user.save()


    else:
        for song in all_song_list:
            rating_dict[song] = '-'
        signin_msg = 'Please create an account or log in to rate songs and follow artists'

    context = {'artist': artist,
    'all_song_list': all_song_list,
    'rating_dict': rating_dict,
    'signin_msg': signin_msg}
    #'songs_without_rating': songs_without_rating,}
    return render(request, 'warehouse/listsongbyartist.html', context)


def SongDetailView(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    avg_rate = song.average_rating
    if request.user.is_anonymous == False:
        rating_obj = Rating.objects.get_or_create(user=request.user, song=song)
        current_rate= rating_obj[0].rate
        if request.method== 'POST':
            rate_form = RateForm(request.POST, instance=rating_obj[0])
            if rate_form.is_valid():

                save_rate_form = rate_form.save(commit=False)
                save_rate_form.song = song
                save_rate_form.rate = rate_form.cleaned_data.get('rate')
                save_rate_form.user = request.user
                save_rate_form.save()

                messages.success(request, f'Your song has been saved!')
                return redirect('/warehouse/', permanent=True)

        else:
            rate_form = RateForm(instance=Rating())
    else:
        current_rate = '-'
        rate_form = 'Please create account or log in to create user ratings'

    context = {'song' : song,'current_rate': current_rate, 'avg_rate': avg_rate, 'rate_form': rate_form,}
    return render(request, 'warehouse/SongDetail.html', context)

@login_required
def AddSong(request):
    if request.method== 'POST':
        # artist_form = ArtistForm(request.POST, prefix='art', instance=Artist())
        # album_form = AlbumForm(request.POST, instance=Album(), prefix='alb')
        song_form = SongForm(request.POST)
        if song_form.is_valid():
            cleaned_data = song_form.cleaned_data
            #check if artist exists, if not - create new objct
            art_name = cleaned_data.get('artist')
            obj_art = Artist.objects.get_or_create(name=art_name)
            if obj_art[1]=='True':
                obj_art[0].save()

            alb_name = cleaned_data.get('album')
            obj_alb = Album.objects.get_or_create(name=alb_name)
            if obj_alb[1]=='True':
                obj_alb[0].save()

            song_name = cleaned_data.get('name')
            new_song = Song.objects.get_or_create(name=song_name, album=obj_alb[0])
            new_song[0].artist.add(obj_art[0])



            messages.success(request, f'Your song has been saved!')
            return redirect('/', permanent=True)
    else:
        print('song invalid')
        song_form = SongForm()


    context = {
         'song_form': song_form,
    }
    return render(request, 'warehouse/addSong.html', context)

# class SongUpdateView(LoginRequiredMixin, UpdateView):
#     model = Song
#     fields = ['name', 'album','artist',]


class SongDeleteView(LoginRequiredMixin, DeleteView):
    model = Song
    success_url = '/'

warehouse/templates/warehouse/SongDetail.html
{% extends 'homepage/base.html' %}
{% block content %}

<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Song Detail View</legend>
                <p> Song Name: {{song.name}} <br>
                  <span style="float:right;">
                   <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'warehouse:song-delete' song.id %}">Delete</a>
                  </span>
                Artist: {% for artist in song.artist.all %}
                  <a href="{% url 'warehouse:listsongbyartist' artist.id %}">{{artist}}</a>
                {% endfor  %} <br>
                Album:
                  <a href="{% url 'warehouse:listsongbyalbum' song.album.id %}">{{song.album}}</a> <br>
                Your Rating: {{current_rate}} <br>
                Average Rating: {{avg_rate}} <br>
                {{rate_form}}
                </p>

        </fieldset>
    </form>
</div>

{% endblock content%}

<!-- {% for artist in artists %}
<a class="mr-2" href="{% url 'artist-detail' artist.art_name %}"> {{ artist.art_name }}</a>
  <p> </p>
{% endfor  %}
              <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'warehouse:song-update' song.id %}">Update</a> 
                {{song.artist.all}}  -->

warehouse/templates/warehouse/addSong.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edit Song Info</legend>
                {{ form|crispy}}

                {{ song_form|crispy }}
                <!-- {{ album_form|crispy }} -->




            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

warehouse/templates/warehouse/index.html
{% extends 'homepage/base.html' %}
{% block content %}


{% if all_artist_list %}
    <ul>
    {% for artist in all_artist_list %}
        <li><a href="{% url 'warehouse:listsongbyartist' artist.id %}">{{ artist.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No artists are available.</p>
{% endif %}
{% endblock content%}

warehouse/templates/warehouse/listsongbyalbum.html
{% extends 'homepage/base.html' %}
{% block content %}

<h1>{{ album.name }}</h1>
<p>{{ signin_msg}} </p>
<p> Average rating of {{album.average_rating}} based on ratings from {{album.rating_count}} users</p>



<table>
  <thead>
    <tr style="text-align: center">
      <th> Song </th>
      <th> Artist </th>
      <th> Average Rating </th>
      <th> User Rating </th>
    </tr>
  </thead>
  <tbody>
      {% for song in all_song_list  %}
        <tr style="text-align: center">
          <td><a href="{% url 'warehouse:SongDetail' song.id %}">{{ song.name }}</a> </td>
          <td>{% for artist in song.artist.all %}
              <a href="{% url 'warehouse:listsongbyartist' artist.id %}">{{artist}}</a>
            {% endfor  %}</td>
          <td>{{song.average_rating}}</td>
          {% for key, value in rating_dict.items %}
            {% if key == song %}
          <td>{{value}}</td>
            {% endif %}
          {% endfor %}
        </tr>
      {% endfor %}
  </tbody>
</table>

{% endblock content%}

warehouse/templates/warehouse/listsongbyartist.html
{% extends 'homepage/base.html' %}
{% block content %}

<h1>{{ artist.name }}
  {% if user.is_authenticated %}
  <form method='post'>
      {% csrf_token %}
      {% if artist in request.user.following.all %}
        <button class="btn btn-outline-danger" name='follow' value='unfollow' type="submit">
        Unfollow </button>
      {% else %}
        <button class="btn btn-outline-success" name='follow' value='follow' type="submit">
          Follow </button>  {% endif %}
  </form>
  <span style="float:right;">
  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'warehouse:addSong' %}">Add new song</a>
  </span>
  {% endif %}
</h1>
<p>{{ signin_msg}} </p>
<p> Average rating of {{artist.average_rating}} based on ratings from {{artist.rating_count}} users </p>



<table class="table">
  <thead>
    <tr style="text-align: center">
      <th> Song </th>
      <th> Album </th>
      <th> Average Rating </th>
      <th> User Rating </th>
    </tr>
  </thead>
  <tbody>
      {% for song in all_song_list  %}
        <tr style="text-align: center">
          <td><a href="{% url 'warehouse:SongDetail' song.id %}">{{ song.name }}</a> </td>
          <td><a href="{% url 'warehouse:listsongbyalbum' song.album.id %}">{{song.album}}</a></td>
          <td>{{song.average_rating}}</td>
          {% for key, value in rating_dict.items %}
            {% if key == song %}
          <td>{{value}}</td>
            {% endif %}
          {% endfor %}
        </tr>
      {% endfor %}
  </tbody>
</table>

{% endblock content%}

warehouse/templates/warehouse/song_confirm_delete.html
{% extends "homepage/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Song</legend>
                <h2>Are you sure you want to delete the song "{{ object.name }}" by
                {% for artist in song.artist.all %}
                    {{artist}}
                  {% endfor  %} ?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'warehouse:SongDetail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

warehouse/templates/warehouse/success.html
Success